CREATE (:Tipo_conceptual_general:_Norma {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"});
CREATE (:Tipo_conceptual_general:_Organizacion {id:"Instituto_Nacional_de_Servicios_Sociales_para_Jubilados_y_Pensionados"});
CREATE (:Tipo_conceptual_general:_Norma {id:"EX_2020_15409689___INSSJP_USA_INSSJP___Reglamento_para_Solicitar_y_Recibir_Informacion_Publica_del_Instituto._"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Ley_19.032"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Ley_27.275"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Decreto_reglamentario_206/PEN/17"});
CREATE (:Tipo_conceptual_general:_Norma {id:"RESOL_2020_1637_INSSJP_DE_INSSJP"});
CREATE (:Tipo_conceptual_general:_Norma {id:"RESOL_2021_1278_INSSJP_DE_INSSJP"});
CREATE (:Tipo_conceptual_general:_Norma. {id:"RESOL_2024_80_APN_AAIP"});
CREATE (:Tipo_conceptual_general:_Norma. {id:"Ley_No_25.615"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Decreto_PEN_No_02/04"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Decreto_No_DECTO_2023_63_APN_PTE"});
CREATE (:Tipo_conceptual_general:_Proceso {id:"Unidad_Secretaria_Administrativa"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Anexo_I_(_IF_2024_76807687_INSSJP_DE_INSSJP_)"});
CREATE (:Tipo_conceptual_general:_Documento. {id:"Anexo_II_(_IF_2024_76807730_INSSJP_DE_INSSJP_)"});
CREATE (:Tipo_conceptual_general:_Norma {id:"REGLAMENTO_PARA_SOLICITAR_Y_RECIBIR_INFORMACION_PUBLICA_DEL_INSTITUTO_NACIONAL_DE_SERVICIOS_SOCIALES_PARA_JUBILADOS_Y_PENSIONADOS."});
CREATE (:Tipo_conceptual_general:_Documento {id:"IF_2024_76807687_INSSJP_DE_INSSJP"});
CREATE (:Tipo_conceptual_general:_Documento {id:"IF_2024_76807730_INSSJP_DE_INSSJP"});
CREATE (:Tipo_conceptual_general:_**Documento**. {id:"Formulario_de_Solicitud_de_Informacion_Publica_del_INSSJP"});
CREATE (:Tipo_conceptual_general:_Norma {id:"Reglamento_de_Gestion_Documental_en_el_INSSJP_PAMI"});
CREATE (:Tipo_conceptual_general:_Proceso {id:"la_plataforma_de_Tramites_a_Distancia_(TAD)"});
CREATE (:Tipo_conceptual_general:_**Registro** {id:"expediente_GDE"});
CREATE (:Tipo_conceptual_general:_Organizacion. {id:"Agencia_de_Acceso_a_la_Informacion_Publica"});
CREATE (:Tipo_conceptual_general:_Documento {id:"Boletin_del_Instituto"});
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"RESOL_2020_1637_INSSJP_DE_INSSJP"}) CREATE (a)-[:DEROGA]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Reglamento_para_Solicitar_y_Recibir_Informacion_Publica_del_INSSJP_(Anexo_I;_IF_2024_76807687_INSSJP_DE_INSSJP)"}) CREATE (a)-[:APRUEBA]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Formulario_de_Solicitud_de_Informacion_Publica_del_INSSJP_(Anexo_II;_IF_2024_76807730_INSSJP_DE_INSSJP)"}) CREATE (a)-[:APRUEBA]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Anexo_I___Reglamento_para_Solicitar_y_Recibir_Informacion_Publica_del_INSSJP_(IF_2024_76807687_INSSJP_DE_INSSJP)"}) CREATE (a)-[:CONTIENE]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Anexo_II___Formulario_de_Solicitud_de_Informacion_Publica_del_INSSJP_(IF_2024_76807730_INSSJP_DE_INSSJP)"}) CREATE (a)-[:CONTIENE]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Articulo_66_del_Reglamento_de_Gestion_Documental_en_el_INSSJP_PAMI,_RESOL_2021_1278_INSSJP_DE_INSSJP_Anexo_I_"}) CREATE (a)-[:MODIFICA]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Boletin_del_Instituto_(publicacion_de_la_resolucion)"}) CREATE (a)-[:REGULA]->(b);
MATCH (a {id:"RESOL_2024_2076_INSSJP_DE_INSSJP"}), (b {id:"Autorizar_a_la_Unidad_Secretaria_Administrativa_a_dictar_normas_complementarias"}) CREATE (a)-[:APRUEBA]->(b);